name: jupyter-clone-${PROJECT_NAME}

services:
  jupyter:
    container_name: jupyter-clone-${PROJECT_NAME}
    build :
      context: .
      dockerfile: Dockerfile
    command: sh -c "start-notebook.sh --IdentityProvider.token=''"
    ports:
      - "8888"
    volumes:
      - type: bind
        source: db/${PROJECT_NAME}
        target: /home/jovyan/
    env_file:
      - path: .env