name: jupyter-clone-${PROJECT_NAME}

services:
  jupyter:
    container_name: jupyter-clone-${PROJECT_NAME}
    build :
      context: .
      dockerfile: Dockerfile
    user: "$(UID):$(GID)"
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888"
    volumes:
      - type: bind
        source: db/${PROJECT_NAME}
        target: /home/jovyan/
    env_file: .env

networks:
  default:
    name: jupyter-clone
    external: true